name: Release

on:
  push:
    tags:
      - 'v*.*.*'   # Se ejecuta solo al empujar un tag vX.Y.Z

permissions:
  contents: write  # Imprescindible para crear la Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug ref (opcional)
        run: echo "ref=$GITHUB_REF type=$GITHUB_REF_TYPE name=$GITHUB_REF_NAME"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Si no tienes package-lock.json, usa npm install
      - name: Install deps
        run: npm install

      - name: Build & publish release
        run: npm run dist -- -w --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # usa el token integrado del workflow